### ISSUE TITLE
Support Task Configuration Avoidance

### ISSUE THREAD

**Issue by sdavids** [xvik/gradle-animalsniffer-plugin#15]
Please support Task Configuration Avoidance:

https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

Your plugin requires 5.x so a [migration](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:task_configuration_avoidance_migration_steps) should be no breaking change.

**Comment by xvik** [comment]
It is already supported (see #13 for example). If you see other places where it could be used please tell me.
