### ISSUE TITLE
Gradle DSL method not found: 'signature()'

### ISSUE THREAD

**Issue by io7m** [xvik/gradle-animalsniffer-plugin#17]
Hello.

I'm trying to include this plugin into a project so that I can check that I'm writing Android-compatible code. Unfortunately, every time I try to add signatures, I get the following error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/rm-work/git/com.github/irradia/one.irradia.mime/build.gradle' line: 118

* What went wrong:
A problem occurred evaluating root project 'one.irradia.mime'.
> Could not find method signature() for arguments [org.codehaus.mojo.signature:java16:1.1@signature] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Please see the `build.gradle` file here:

https://github.com/irradia/one.irradia.mime/blob/747f6b187d21f3fc9f5d151ef7aba92e3dc99110/build.gradle#L117

If I uncomment the `dependencies` section there, the above error appears.

Am I doing something wrong?

**Comment by xvik** [comment]
Hello! 

The plugin simply [not support android yet](https://github.com/xvik/gradle-animalsniffer-plugin/issues/8). It works only if `java` plugin applied, which is not used in case of android project.

As I can see, in your build, subprojects use java plugin when POM_PACKAGING="jar", so animalsniffer plugin could work on these subprojects (not on root project), but only for jar packaging case.

**Comment by io7m** [comment]
Ah, ok, thanks! I'll only apply it for `jar` packaging.
