### ISSUE TITLE
simplefilecollection has been deprecated

### ISSUE THREAD

**Issue by ConradKrinock** [xvik/gradle-animalsniffer-plugin#20]
Reviving issue:  https://github.com/xvik/gradle-animalsniffer-plugin/issues/9

  - has anything changed recently that would cause this error, or
  -  Can you provide any guidance to help us self-diagnose this issue?

Vyacheslav Rusakov had previously reported: "Quite possible - it's not the first
     time when they change this base class (base for all quality plugins). 
     I just started fixing all my plugins for gradle 4.8."

Possibly one of our plugins is using the deprecated class(?)

We are currently on version 4.10.3.

Thanks / RSVP,

Conrad Krinock
     Cyber Security Architect
      conradk@flash.net

**Comment by xvik** [comment]
As I understand, you have a warning message of deprecated gradle api usage.

The original problem has been resolved in 1.4.4, but you can use 1.4.6 (the latest gradle 4 compatible release).

If you already using correct version then enable gradle warnings to see exact source:

```
gradlew clean --warning-mode=all
```

It should show the exact place (plugin) causing your warning.
