### ISSUE TITLE
Support gradle configuration cache

### ISSUE THREAD

**Issue by yschimke** [xvik/gradle-animalsniffer-plugin#26]
Trying to optimise my build with a build cache and finding issues with supported plugins. Not urgent, but flagging as it may affect others also.

```
- Task `:mockwebserver-deprecated:animalsnifferMain` of type `ru.vyarus.gradle.plugin.animalsniffer.AnimalSniffer`: cannot serialize object of type 'org.gradle.api.internal.tasks.DefaultSourceSet', a subtype of 'org.gradle.api.tasks.SourceSet', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.0/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```

**Comment by xvik** [comment]
Thank you! I'll try to look it this week

**Comment by xvik** [comment]
I looked configuration cache problem: it's not hard to support but would require a breaking change - changing task parameter type. Also, configuration cache is in experimental state and even gradle itself does not support it completely (so I doubt it's widely used).

I don't deny this, just postpone for some time. If this would be critically important, please ping me.

And I just released a new version with fixed gradle 7 deprecation warnings.

**Comment by Goooler** [comment]
Gradle 7.4 introduces a feature to declare that individual tasks are incompatible with the configuration cache, allowing the feature to be enabled by default while skipping caching when there are tasks don't support it.

https://docs.gradle.org/7.4/release-notes.html#config-cache

**Comment by xvik** [comment]
It appears that I can fix warnings, so now it should work properly. 
Will release new version soon (with animalsniffer 1.22)
