### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by jcayzac** [xvik/gradle-animalsniffer-plugin#6]
Hi,
Could you make a sample project available in the repo?
I'm using this in a java library project (`java-library` plugin, using gradle 4.3) and I cannot get it to fail even when I set it up to use JDK 1.3 signatures, while my library uses `ByteBuffer` (introduced in 1.4).
Thanks.

**Comment by xvik** [comment]
Hi!
I'm using it in many projects and so far it was working :)
For example, https://github.com/xvik/guice-persist-orient/blob/master/build.gradle#L28

In theory, it should work with java-library plugin (which I don't use). 
Can you show me your project? If not, I will try to reproduce myself

**Comment by xvik** [comment]
I tried gradle 4.3 and java-library plugin and did not found any issues.
I need to know more about your project (ideally, see your build file) in order to help because it looks like a configuration problem.

**Comment by xvik** [comment]
I suppose you have found a solution. Please reopen if you still need help.

**Comment by jcayzac** [comment]
@xvik sorry for the delay! I haven't been able to work on the project I mentioned for the past two weeks, as lots of other things came in. Thanks for looking into it, and for the super-quick reply.

**Comment by xvik** [comment]
No problem, ask me if you still have any problems.
