### ISSUE TITLE
Issues targeting Java 17, building with Java 21

### ISSUE THREAD

**Issue by pholser** [xvik/gradle-animalsniffer-plugin#88]
Firstly -- thanks for an extremely useful project. Nicely done!

On [this project](https://github.com/pholser/duly-noted), I'm in the process of upversioning dependencies, building on Java 21, targeting Java 17.

I'm getting several AnimalSniffer plugin errors, mostly around Optionals and Streams, e.g.:

```
> Task :animalsnifferMain FAILED

[Undefined reference] com.pholser.dulynoted.(AbstractMeta.java:31)
  >> java.util.Optional

[Undefined reference] com.pholser.dulynoted.(AbstractMeta.java:39)
  >> java.util.Optional

[Undefined reference] com.pholser.dulynoted.(AbstractMeta.java:39)
  >> java.util.function.Supplier

[Undefined reference] com.pholser.dulynoted.(AbstractMeta.java:40)
  >> java.util.Optional java.util.Optional.or(java.util.function.Supplier)
```

Any ideas what I may be missing?

**Comment by xvik** [comment]
```
signature 'org.codehaus.mojo.signature:java17:1.0@signature'
```
This is actually java 1.7 signatires, which explains all the errors.

There is [no signatires for java 9+](https://github.com/mojohaus/animal-sniffer/issues/62):

```
Starting with JDK9+ you can't define a full API signature cause based on the module system you can define your own (limited view on JDK). Apart from that you can use the release configuration in maven-compiler-plugin with JDK9+ to have exactly what animal sniffer offers and that's the reason why there are no JDK9+ signatures.
```

You need to use [--release flag](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:compiling_with_release) instead of animalsniffer:

```java
compileJava {
    options.release = 17
}
```
